import "@styles/globals.css";
import "nprogress/nprogress.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import Navigation from "./components/navigation";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "TCPC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
